import { describe, it, expect } from "vitest";
import {
  cleanConfluenceTitle,
  confluenceBreadcrumbs,
  htmlTitle,
  htmlToDoc,
  parseConfluenceIndex,
} from "./html";
import { findNodes } from "./doc";
import { extractText } from "./text";

const CONFLUENCE_PAGE = `<!DOCTYPE html>
<html><head><title>DEV : Deployment - Confluence</title><style>body{}</style></head>
<body>
<div id="page">
<div id="main-header"><div id="breadcrumb-section"><ol id="breadcrumbs">
<li class="first"><span><a href="index.html">DEV</a></span></li>
<li><span><a href="Handbuch_100.html">Handbuch</a></span></li>
<li><span><a href="Betrieb_200.html">Betrieb</a></span></li>
</ol></div>
<h1 id="title-heading" class="pagetitle"><span id="title-text">DEV : Deployment</span></h1></div>
<div id="content" class="view">
<div id="main-content" class="wiki-content group">
<p>Einleitung mit <a href="Betrieb_200.html">Link</a>.</p>
<div class="confluence-information-macro confluence-information-macro-note"><span class="aui-icon aui-icon-small aui-iconfont-warning confluence-information-macro-icon">Icon</span><div class="confluence-information-macro-body"><p>Achtung, Wartung.</p></div></div>
<div class="confluence-information-macro confluence-information-macro-information"><p class="title">Info</p><span class="aui-icon">Icon</span><div class="confluence-information-macro-body"><p>Nur Info.</p></div></div>
<div class="code panel pdl"><div class="codeContent panelContent pdl">
<pre class="syntaxhighlighter-pre" data-syntaxhighlighter-params="brush: bash; gutter: false; theme: Confluence" data-theme="Confluence">docker compose up -d
  echo "eingerueckt"</pre>
</div></div>
<ul class="inline-task-list" data-inline-tasks-content-id="1">
<li data-inline-task-id="1" class="checked">Erledigt</li>
<li data-inline-task-id="2">Offen</li>
</ul>
<div class="table-wrap"><table class="confluenceTable"><tbody><tr><th class="confluenceTh">Spalte</th></tr><tr><td class="confluenceTd">Wert</td></tr></tbody></table></div>
<p><span class="confluence-embedded-file-wrapper"><img class="confluence-embedded-image" src="attachments/123/456.png"></span><img class="emoticon emoticon-tick" src="images/icons/emoticons/check.svg"></p>
<div class="pageSection group"><div class="pageSectionHeader"><h2>Attachments:</h2></div><ul><li><a href="attachments/123/456.png">456.png</a></li></ul></div>
</div></div>
<div id="footer">Document generated by Confluence</div>
</div></body></html>`;

describe("Confluence-HTML", () => {
  it("Titel ohne Space-Praefix und Suffix", () => {
    expect(cleanConfluenceTitle("DEV : Deployment - Confluence")).toBe("Deployment");
    expect(cleanConfluenceTitle("Seite")).toBe("Seite");
    expect(htmlTitle(CONFLUENCE_PAGE, "confluence")).toBe("Deployment");
    expect(htmlTitle("<title>DEV : Nur Title</title>", "confluence")).toBe("Nur Title");
  });

  it("nutzt nur #main-content und bildet Makros ab", () => {
    const { title, doc } = htmlToDoc(CONFLUENCE_PAGE, "confluence");
    expect(title).toBe("Deployment");
    const text = extractText(doc);
    expect(text).not.toContain("Document generated");
    expect(text).not.toContain("Icon");
    expect(text).not.toContain("Attachments");

    const callouts = findNodes(doc, "callout");
    expect(callouts.map((c) => c.attrs?.type)).toEqual(["warn", "info"]);
    expect(extractText(callouts[0])).toBe("Achtung, Wartung.");
    expect(extractText(callouts[1])).toContain("Info");

    const code = findNodes(doc, "codeBlock");
    expect(code).toHaveLength(1);
    expect(code[0].attrs?.language).toBe("bash");
    expect(code[0].content?.[0].text).toBe('docker compose up -d\n  echo "eingerueckt"');

    const tasks = findNodes(doc, "taskItem");
    expect(tasks.map((t) => t.attrs?.checked)).toEqual([true, false]);

    expect(findNodes(doc, "table")).toHaveLength(1);
    expect(findNodes(doc, "tableHeader")).toHaveLength(1);

    const images = findNodes(doc, "image");
    expect(images).toHaveLength(1);
    expect(images[0].attrs?.src).toBe("attachments/123/456.png");
  });

  it("Breadcrumbs liefern die Elternkette ohne index.html", () => {
    expect(confluenceBreadcrumbs(CONFLUENCE_PAGE)).toEqual([
      "Handbuch_100.html",
      "Betrieb_200.html",
    ]);
  });

  it("index.html liefert die Hierarchie", () => {
    const index = `<html><body><div id="main-content" class="pageSection">
<div class="pageSectionHeader"><h2 class="pageSectionTitle">Available Pages:</h2></div>
<ul>
<li><a href="Handbuch_100.html">Handbuch</a><img src="images/icons/contenttypes/home_page_16.png">
<ul>
<li><a href="Betrieb_200.html">Betrieb</a>
<ul><li><a href="Deployment_300.html">Deployment</a></li></ul>
</li>
<li><a href="FAQ_400.html">FAQ</a></li>
</ul>
</li>
</ul></div></body></html>`;
    expect(parseConfluenceIndex(index)).toEqual([
      {
        href: "Handbuch_100.html",
        title: "Handbuch",
        children: [
          {
            href: "Betrieb_200.html",
            title: "Betrieb",
            children: [{ href: "Deployment_300.html", title: "Deployment", children: [] }],
          },
          { href: "FAQ_400.html", title: "FAQ", children: [] },
        ],
      },
    ]);
  });
});

const NOTION_PAGE = `<html><head><meta charset="utf-8"><title>Roadmap</title><style>.x{}</style></head>
<body><article id="abc" class="page sans">
<header><h1 class="page-title">Roadmap 2026</h1></header>
<div class="page-body">
<h1 id="1">Roadmap 2026</h1>
<p id="2" class="">Siehe <a href="Roadmap%2012ab34cd12ab34cd12ab34cd12ab34cd/Q1%20ffffffffffffffffffffffffffffffff.html">Q1</a>.</p>
<ul id="3" class="to-do-list">
<li><div class="checkbox checkbox-on"></div> <span class="to-do-children-checked">Fertig</span></li>
<li><div class="checkbox checkbox-off"></div> <span class="to-do-children-unchecked">Offen</span></li>
</ul>
<figure class="callout" style="white-space:pre-wrap;display:flex"><div style="font-size:1.5em"><span class="icon">💡</span></div><div style="width:100%">Merke dir das.</div></figure>
<ul id="4" class="toggle"><li><details open=""><summary>Details</summary><p>Versteckter Text</p></details></li></ul>
<pre id="5" class="code"><code class="language-Python">print("hi")</code></pre>
<pre id="6" class="code"><code class="language-Mermaid">graph LR; A-->B;</code></pre>
<figure id="7" class="image"><a href="Roadmap%2012ab34cd12ab34cd12ab34cd12ab34cd/bild.png"><img style="width:600px" src="Roadmap%2012ab34cd12ab34cd12ab34cd12ab34cd/bild.png"/></a></figure>
<table class="simple-table"><tbody><tr><td>a</td><td>b</td></tr></tbody></table>
</div></article></body></html>`;

describe("Notion-HTML", () => {
  it("Titel aus h1.page-title, H1-Duplikat im Body wird entfernt", () => {
    expect(htmlTitle(NOTION_PAGE, "notion")).toBe("Roadmap 2026");
    const { title, doc } = htmlToDoc(NOTION_PAGE, "notion");
    expect(title).toBe("Roadmap 2026");
    expect(findNodes(doc, "heading")).toHaveLength(0);
  });

  it("Checkboxen, Callouts, Toggles, Code und Bilder", () => {
    const { doc } = htmlToDoc(NOTION_PAGE, "notion");
    const tasks = findNodes(doc, "taskItem");
    expect(tasks.map((t) => t.attrs?.checked)).toEqual([true, false]);
    expect(extractText(tasks[0]).trim()).toBe("Fertig");

    const callouts = findNodes(doc, "callout");
    expect(callouts).toHaveLength(1);
    expect(extractText(callouts[0]).trim()).toBe("Merke dir das.");
    expect(extractText(doc)).not.toContain("💡");

    // Toggle: Titel fett als Absatz, Inhalt als Absatz — keine Liste
    expect(findNodes(doc, "bulletList")).toHaveLength(0);
    const bold = findNodes(doc, "paragraph").find((p) =>
      p.content?.some((c) => c.marks?.some((m) => m.type === "bold")),
    );
    expect(extractText(bold!)).toBe("Details");
    expect(extractText(doc)).toContain("Versteckter Text");

    const code = findNodes(doc, "codeBlock");
    expect(code).toHaveLength(1);
    expect(code[0].attrs?.language).toBe("python");
    expect(findNodes(doc, "mermaid")[0].attrs?.code).toBe("graph LR; A-->B;");

    const img = findNodes(doc, "image");
    expect(img).toHaveLength(1);
    expect(img[0].attrs?.src).toContain("bild.png");
    expect(findNodes(doc, "table")).toHaveLength(1);
  });

  it("Links bleiben mit Original-href (Aufloesung passiert spaeter)", () => {
    const { doc } = htmlToDoc(NOTION_PAGE, "notion");
    const link = findNodes(doc, "paragraph")
      .flatMap((p) => p.content ?? [])
      .find((n) => n.marks?.some((m) => m.type === "link"));
    expect(link?.marks?.[0].attrs?.href).toContain("Q1%20ffffffff");
  });
});

describe("generisches HTML", () => {
  it("Titel aus <title>, Inhalt aus body, script/style verworfen", () => {
    const html =
      "<html><head><title>Seite X</title><script>alert(1)</script></head><body><nav>Menu</nav><h1>Seite X</h1><p>Hallo <b>Welt</b></p><ul><li><input type=\"checkbox\" checked> A</li><li><input type=\"checkbox\"> B</li></ul></body></html>";
    const { title, doc } = htmlToDoc(html, "markdown");
    expect(title).toBe("Seite X");
    const text = extractText(doc);
    expect(text).not.toContain("alert");
    expect(text).not.toContain("Menu");
    expect(findNodes(doc, "heading")).toHaveLength(0);
    expect(findNodes(doc, "taskItem").map((t) => t.attrs?.checked)).toEqual([true, false]);
  });

  it("<title> im head wird gelesen, landet aber nicht im Inhalt", () => {
    const { title, doc } = htmlToDoc(
      "<html><head><meta charset=\"utf-8\"><title>Nur im Head</title></head><body><p>Inhalt</p></body></html>",
      "confluence",
    );
    expect(title).toBe("Nur im Head");
    expect(extractText(doc)).toBe("Inhalt");
    // ohne <body>: Titel trotzdem nicht im Inhalt
    const bare = htmlToDoc("<title>T</title><p>Nur Text</p>", "markdown");
    expect(bare.title).toBe("T");
    expect(extractText(bare.doc)).toBe("Nur Text");
  });

  it("Titel-Fallback auf erste H1", () => {
    expect(htmlTitle("<body><h1>Nur &amp; H1</h1></body>", "markdown")).toBe("Nur & H1");
    expect(htmlTitle("<p>nichts</p>", "markdown")).toBeNull();
  });
});
