/**
 * Variablen, die es schon gab und die noch keine Deklaration im Schema
 * haben. Die Pruefung beim Start liest sie nicht; das Startlog nennt nur
 * die Namen der gesetzten (`unchecked`), nie ihre Werte.
 *
 * Die Liste schrumpft nur: wer eine dieser Variablen deklariert, streicht
 * sie hier. Neue Variablen kommen nie hierher, sondern ins Schema
 * (README.md dieses Pakets). apps/web/src/konfiguration.test.ts haelt die
 * Liste sortiert und gleich mit .env.example und den Compose-Dateien.
 */
export const NOCH_OHNE_SCHEMA: readonly string[] = [
  "AI_INDEX_EMBED_BATCH",
  "AI_INDEX_INTERVAL_S",
  "AI_MODEL",
  "ANTHROPIC_API_KEY",
  "APP_BIND",
  "APP_BIND6",
  "APP_NAME",
  "APP_PORT",
  "APP_SECRET",
  "APP_URL",
  "AUDIT_RETENTION_DAYS",
  "BACKUP_KEEP_DAYS",
  "CADDY_TLS",
  "COLLAB_MAX_ATTEMPTS_PER_IP",
  "COLLAB_MAX_ATTEMPTS_PER_USER",
  "COLLAB_MAX_CONNECTIONS",
  "COLLAB_MAX_CONNECTIONS_PER_IP",
  "COLLAB_MAX_CONNECTIONS_PER_USER",
  "COLLAB_MAX_DOC_MB",
  "COLLAB_MAX_MESSAGE_MB",
  "COLLAB_PORT",
  "COMPOSE_FILE",
  "DATABASE_URL",
  "DEBUG_DB",
  "DIGEST_HOUR_UTC",
  "EMBEDDING_MODEL",
  "GOTENBERG_URL",
  "IMPORT_MAX_CONCURRENT",
  "IMPORT_MAX_MB",
  "IMPORT_TIMEOUT_S",
  "INVITE_LINK_WITHOUT_MAIL",
  "JWT_EXPIRES_IN",
  "MAIL_DISPATCH_INTERVAL_S",
  "MAX_UPLOAD_MB",
  "NEXT_PUBLIC_COLLAB_URL",
  "NODE_ENV",
  "NOTIFICATION_RETENTION_DAYS",
  "OIDC_ALLOW_SIGNUP",
  "OIDC_AUTO_LINK_BY_EMAIL",
  "OIDC_BUTTON_LABEL",
  "OIDC_CLIENT_ID",
  "OIDC_CLIENT_SECRET",
  "OIDC_ISSUER",
  "OIDC_SCOPES",
  "POSTGRES_PASSWORD",
  "REDIS_PASSWORD_FILE",
  "REDIS_URL",
  "SESSION_IDLE_TIMEOUT",
  "SESSION_RETENTION_DAYS",
  "SITE_ADDRESS",
  "SMTP_HOST",
  "SMTP_PASSWORD",
  "SMTP_PORT",
  "SMTP_SECURE",
  "SMTP_USERNAME",
  "TOKEN_RETENTION_DAYS",
  "TRASH_RETENTION_DAYS",
  "TRUSTED_PROXY_HOPS",
  "UPLOAD_DIR",
  "UPLOAD_SWEEP_INTERVAL_H",
  "VERSION_RETENTION",
  "VOYAGE_API_KEY",
];
